### ISSUE TITLE
It will crash when start, and Xitu's api changed.

### ISSUE THREAD

**Issue by JeasonWong** [lulee007/Xitu#1]
It will crash when start, and Xitu's api changed.

api maybe need 
- X-LC-Sign
- X-LC-Id
- Accept-Encoding=>gzip

**Comment by lulee007** [comment]
@JeasonWong  updated  
[XTBaseService.java](https://github.com/lulee007/Xitu/blob/aadadff67e008dfeddbf43653a65f39f40ebd365/app/src/main/java/com/lulee007/xitu/Base/XTBaseService.java)

 new headers :
* X-LC-Prod
* X-LC-Session
* X-LC-Id
* X-LC-Sign
* X-Android-RS
